# Generated by Django 4.0.10 on 2025-03-26 14:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sensor', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Appliance',
            fields=[
                ('appliance_id', models.IntegerField(primary_key=True, serialize=False)),
                ('appliance_name', models.CharField(max_length=15)),
                ('power_rating_w', models.IntegerField()),
            ],
            options={
                'db_table': 'appliances_table',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='ScenarioSummary',
            fields=[
                ('scenario_id', models.AutoField(primary_key=True, serialize=False)),
                ('time_slot', models.CharField(max_length=9)),
                ('power_consumed_w', models.IntegerField()),
                ('duration_hrs', models.IntegerField()),
                ('scenario_type', models.CharField(max_length=8)),
                ('reason_for_abnormality', models.CharField(max_length=40)),
            ],
            options={
                'db_table': 'scenario_summary_table',
                'managed': False,
            },
        ),
        migrations.AlterModelOptions(
            name='sensordata',
            options={'managed': False},
        ),
    ]
